# BBTravis CI configuration file

language: python
python:
  - "2.7"

env:
  matrix:
  - TESTS=trial
  - TESTS=lint

install:
  - pip install -U pip
  - |
      # pip installs
      set -e
      pip install twisted
      pip install -e .

# Tests running commands
script:
  - condition: TESTS == 'trial'
    cmd: trial pyflakes
  - condition: TESTS == 'lint'
    cmd: pyflakes pyflakes
